apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-krr-enforcer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: krr-enforcer
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-krr-enforcer
  labels:
    app.kubernetes.io/component: krr-enforcer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-krr-enforcer
  labels:
    app.kubernetes.io/component: krr-enforcer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-krr-enforcer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-krr-enforcer
    namespace: {{ .Release.Namespace }}
