name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'genuine-flight-317411'
        workload_identity_provider: 'projects/429189597230/locations/global/workloadIdentityPools/github/providers/robusta-repos'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: genuine-flight-317411

    - name: Configure Docker Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        tags: |
          robustadev/krr:${{ github.ref_name }}
          us-central1-docker.pkg.dev/genuine-flight-317411/devel/krr:${{ github.ref_name }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1