name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        tags: robustadev/krr:${{ github.ref_name }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: genuine-flight-317411
        export_default_credentials: true

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication	
    - name: Configure Docker	
      run: |-	
        gcloud auth configure-docker us-central1-docker.pkg.dev	

    - name: Verify gcloud configuration	
      run: |-	
        gcloud config get-value project

    - name: Release Docker to old repo
      run: |-
        docker buildx build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --platform linux/arm64,linux/amd64 \
        --cache-from robustadev/krr:${{ github.ref_name }} \
        --tag us-central1-docker.pkg.dev/genuine-flight-317411/devel/krr:${{ github.ref_name }} \
        --push \
        .
