name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/get-python-version
      id: get_version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ steps.get_version.outputs.python-version }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest
