# @format

name: Update Version

on:
  push:
    tags:
      - "v*"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Fetch all branches
        run: git fetch --all

      - name: Select main branch
        run: git checkout origin/main

      - name: Update version in pyproject.toml
        run: |
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Update version in robusta_krr/__init__.py
        run: |
          sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" robusta_krr/__init__.py

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml robusta_krr/__init__.py
          git commit -m "Update version to $VERSION" && git push
